# Ubuntu 16.04 with Java 8 installed

FROM ubuntu:16.04
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y less software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
	apt-get install oracle-java8-set-default && \
	apt-get install unzip && \
    apt-get clean

ADD me.test.client-0.0.1.zip .
RUN unzip -q me.test.client-0.0.1.zip && \
    rm me.test.client-0.0.1.zip && \
    mv me.test.client-* me.test.client && \
    chmod +x me.test.client/bin/start.sh && \
    chmod +x me.test.client/bin/stop.sh && \
    sed -i -e 's/\r$//' me.test.client/bin/start.sh && \
    sed -i -e 's/\r$//' me.test.client/bin/stop.sh

EXPOSE 8090

ENTRYPOINT ["/me.test.client/bin/start.sh"]
CMD ["--console"]